// <auto-generated />
using System;
using Game2048.Game;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Game2048.Game.Migrations
{
    [DbContext(typeof(Game2048DbContext))]
    partial class Game2048DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("MySql:CharSet", "utf8mb4");

            modelBuilder.Entity("Game2048.Game.LeaderboardEntryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BestScore")
                        .HasColumnType("int");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerName")
                        .IsUnique();

                    b.HasAnnotation("MySql:CharSet", "utf8mb4");

                    b.ToTable("LeaderboardEntries");
                });

            modelBuilder.Entity("Game2048.Game.SavedGameEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BoardJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("MySql:CharSet", "utf8mb4");

                    b.Property<bool>("LeakedShouldAddTile")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Lose")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("SavedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<bool>("ScoreRecorded")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SlotKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4");

                    b.Property<bool>("Win")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("SlotKey")
                        .IsUnique();

                    b.HasAnnotation("MySql:CharSet", "utf8mb4");

                    b.ToTable("SavedGames");
                });
#pragma warning restore 612, 618
        }
    }
}
